### ISSUE TITLE
Keeping org window active

### ISSUE THREAD

**Issue by aerique** [jakebox/org-preview-html#10]
Hello, I'm curious if the following is an issue or a problem with my config (which I haven't able to figure out yet).

If I have the frame split in two windows (left and right) and I activate org-preview-html-mode and save my org file, the HTML preview gets displayed in both windows and the cursor is active in the right window (while I was working on an org file in the left window).

I had to modify `org-preview-html/preview` as follows:

     (defun org-preview-html/preview ()
       "Export current org-mode buffer to a temp file and call `eww-open-file' to preview it."
       (interactive)
    +  (when (<= (length (window-list)) 1)
    +    (split-window-horizontally))
       ;; temp filename into a buffer local variable
       (unless org-preview-html/htmlfilename
         (setq org-preview-html/htmlfilename (concat buffer-file-name (make-temp-name "-") ".html")))
       (let ((cb (current-buffer)))
         (save-excursion
    -      (with-selected-window (display-buffer (get-buffer-create "*eww*"))
    -        (let ((eww-point (point))
    -              (eww-window-start (window-start)))
    -          (with-current-buffer cb
    -            (org-export-to-file 'html org-preview-html/htmlfilename nil nil nil nil nil #'eww-open-file))
    -          (goto-char eww-point)
    -          (set-window-start nil eww-window-start)))))
    +      (let ((eww-point (point))
    +            (eww-window-start (window-start)))
    +        (with-current-buffer cb
    +          (org-export-to-file 'html org-preview-html/htmlfilename nil nil nil nil nil #'eww-open-file))
    +        (goto-char eww-point)
    +        (set-window-start nil eww-window-start))))
    +  (other-window -1)
       (add-hook 'kill-buffer-hook #'org-preview-html//cleanning-the-preview nil t))

Is this a know issue or do I have to dive into my config?

(The `split-window` line is when starting from a one window frame and `other-window` line is to make the cursor go back to the org window.)

**Comment by lujun9972** [comment]
Sorry, I have no idea what is happenning. It works properly in my machine.
May be there is something with  `display-buffer`,but I'm not sure.
This function is a bit convoluted. Hope some other guy could help.

**Comment by aerique** [comment]
Ok thanks, I'll do a deep dive into my own setup!

**Comment by lujun9972** [comment]
I will keep it open, so someboy will see it and help fixing it
