### ISSUE TITLE
Error when starting org-preview-html-mode:  Output file not writable

### ISSUE THREAD

**Issue by benprew** [jakebox/org-preview-html#19]
Issue:

In my version of emacs (29.0.50), this setq function 

```
  (setq-local org-preview-html--html-file (concat (file-name-sans-extension buffer-file-name) ".html"))
```

Sets this as the value:
```
"/home/ben/src/ostep-class/w15/ch_32_homework.html"
```

Then when the export command is called:

```
(org-export-to-file 'html (substring org-preview-html--html-file 7)
	  nil org-preview-html-subtree-only nil nil nil nil)
```

the substring command trims the filename to:

```
"en/src/ostep-class/w15/ch_32_homework.html"
```

which causes the error: 

```
helm-M-x-execute-command: Output file not writable
```

Removing the substring function fixes the error (for me). 

Emacs version:

> GNU Emacs 29.0.50 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.34, cairo
 version 1.17.6) of 2022-07-14

**Comment by jakebox** [comment]
Thanks for the report. I don't know how this slipped me. It happened when I changed the way the filepath is stored.

**Comment by benprew** [comment]
Thanks for fixing it so quickly!
