### ISSUE TITLE
Toggle preview/edit

### ISSUE THREAD

**Issue by mlinchitstest** [jakebox/org-preview-html#9]
Can you **please** advise how to get the following functionality (and perhaps add it as option to your package): 

1.  Open every .org file in eww full-window by **default**
2.  Toggle into "edit mode" on demand, also in maximized buffer.
3.  When you click on a link within eww preview, youre taken to another eww preview. When you toggle edit mode in the newly previewed file, you are editing its associated .org file.

In other  words, I'm trying to make org-mode function like an html **wiki**, where you browse pages and toggle edit when you need to change something. Side by side live preview is a cool option, but the main thing is to toggle between these two. Really desperate to get this functionality. Thanks.

**Comment by lujun9972** [comment]
It's a good idea. But It seems too hard for me to implement it.....
I'll leave this issue open, may be someone could help

**Comment by mlinchitstest** [comment]
I didn't know it was that tricky, but I don't know emacs lisp. Thanks.

**Comment by jakebox** [comment]
I think that this idea is out of the scope of this project. Maybe you could consider some sort of ~ox-hugo~ setup? I know you can allow editing with that.
